/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "stdio.h"
#include "Typedefs.h"  // Defined Header file (AUTOSAR Convention)


# define System_Clock_RCC *((vuint32* )(0x400FE000 + 0x108))
# define GPIO_PortF_DIR   *((vuint32* )(0x40025000 + 0x400))
# define GPIO_PortF_DEN   *((vuint32* )(0x40025000 + 0x51c))
# define GPIO_PortF_Data  *((vuint32* )(0x40025000 + 0x3fc))

vuint32 clock_delay; // Defining a delay type to the System Clock  
vuint32 Led_delay;   // Defining a delay type to Led Toggle

typedef union {
			vuint32 ALLPORT;
		struct{
			vuint32 reserved:3;
			vuint32 Pin13:1;
		}Pin;
}PortF;

volatile PortF* PF = (volatile PortF*)(0x400253fc);

int main(){

//Enabling the system clock to enable the GPIO Peripheral 
System_Clock_RCC |= 0x20;   

/* Ensuring that the clock pulse signal has enough time to completely 
	start and get transfered */ 
for(clock_delay = 0; clock_delay < 200; clock_delay++);

GPIO_PortF_DIR |= 1<<3; // Enabling pin13 to be an output 
GPIO_PortF_DEN |= 1<<3; // Enabling pin13 to be ON

while(1){

	PF->Pin.Pin13 = 1;
	for(Led_delay = 0; Led_delay < 6000; Led_delay++);
	PF->Pin.Pin13 = 0;
	for(Led_delay = 0; Led_delay < 6000; Led_delay++);

		  } 
return 0;
}



